name: Build and deploy Maven artifacts

on:
  push:
    branches:
    - main
    - 7.2.*
    - 7.3.*
    tags:
    - '**'

jobs:
  build:
    name: Build and deploy Maven artifacts

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: Configure cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create settings.xml
      uses: whelk-io/maven-settings-xml-action@v12
      with:
        servers: '[{ "id": "salespoint", "username": "${env.FTP_USER}", "password": "${env.FTP_PASSWORD}" }]'

    - name: Add TU Dresden to known hosts
      env:
        KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      run: |
        mkdir -p ~/.ssh/
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Deploy artifacts
      env:
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: mvn -B deploy -DskipTests --file pom.xml
